-- 酒店收藏表
CREATE TABLE IF NOT EXISTS hotel_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES wechat_users(id) ON DELETE CASCADE,
  hotel_id BIGINT NOT NULL REFERENCES hotels(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, hotel_id)
);

CREATE INDEX IF NOT EXISTS idx_hotel_favorites_user_id ON hotel_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_hotel_favorites_hotel_id ON hotel_favorites(hotel_id);

-- 添加收藏函数
CREATE OR REPLACE FUNCTION add_favorite(p_hotel_id BIGINT, p_openid TEXT)
RETURNS TABLE(success BOOLEAN, message TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_uuid UUID;
BEGIN
  SELECT w.id INTO STRICT v_user_uuid FROM wechat_users w WHERE w.openid = p_openid;
  IF EXISTS (SELECT 1 FROM hotel_favorites WHERE user_id = v_user_uuid AND hotel_id = p_hotel_id) THEN
    RETURN QUERY SELECT TRUE, '已收藏';
  END IF;

  INSERT INTO hotel_favorites (user_id, hotel_id) VALUES (v_user_uuid, p_hotel_id);
  RETURN QUERY SELECT TRUE, '收藏成功';

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN QUERY SELECT FALSE, '用户不存在';
    WHEN OTHERS THEN
      RETURN QUERY SELECT FALSE, SQLERRM;
END;
$$;

-- 取消收藏函数
CREATE OR REPLACE FUNCTION remove_favorite(p_hotel_id BIGINT, p_openid TEXT)
RETURNS TABLE(success BOOLEAN, message TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_uuid UUID;
BEGIN
  SELECT w.id INTO STRICT v_user_uuid FROM wechat_users w WHERE w.openid = p_openid;

  DELETE FROM hotel_favorites WHERE user_id = v_user_uuid AND hotel_id = p_hotel_id;
  RETURN QUERY SELECT TRUE, '取消收藏成功';

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN QUERY SELECT FALSE, '用户不存在';
    WHEN OTHERS THEN
      RETURN QUERY SELECT FALSE, SQLERRM;
END;
$$;

-- 获取用户收藏列表函数
CREATE OR REPLACE FUNCTION get_user_favorites(p_openid TEXT)
RETURNS TABLE(
  id BIGINT,
  hotel_id BIGINT,
  hotel_name TEXT,
  hotel_address TEXT,
  hotel_image TEXT,
  hotel_star_rating SMALLINT,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_uuid UUID;
BEGIN
  SELECT w.id INTO STRICT v_user_uuid FROM wechat_users w WHERE w.openid = p_openid;

  RETURN QUERY
  SELECT
    f.id,
    f.hotel_id,
    h.name_zh AS hotel_name,
    h.address AS hotel_address,
    h.image AS hotel_image,
    h.star_rating AS hotel_star_rating,
    f.created_at
  FROM hotel_favorites f
  JOIN hotels h ON f.hotel_id = h.id
  WHERE f.user_id = v_user_uuid
  ORDER BY f.created_at DESC;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN;
    WHEN OTHERS THEN
      RAISE;
END;
$$;

-- 检查是否已收藏函数
CREATE OR REPLACE FUNCTION check_is_favorited(p_hotel_id BIGINT, p_openid TEXT)
RETURNS TABLE(is_favorited BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_uuid UUID;
  v_is_favorited BOOLEAN := FALSE;
BEGIN
  SELECT w.id INTO v_user_uuid FROM wechat_users w WHERE w.openid = p_openid;
  
  IF v_user_uuid IS NOT NULL THEN
    SELECT EXISTS(SELECT 1 FROM hotel_favorites WHERE user_id = v_user_uuid AND hotel_id = p_hotel_id) INTO v_is_favorited;
  END IF;

  RETURN QUERY SELECT v_is_favorited;
END;
$$;

NOTIFY pgrst, 'reload schema';
